### ISSUE TITLE
Does not work anymore 

### ISSUE THREAD

**Issue by wieland-s** [fbngrmr/audiotheker#7]
Hey there, 

thanks for the great tool. I used it several times and it worked great! 

Unfortunately, however, it no longer works. The command does nothing and exits. 
```
./build/audiotheker download https://www.ardaudiothek.de/sendung/cixin-liu-trisolaris-trilogie-sci-fi-hoerspiel-serie-wdr/13220399
```
I have also tried some urls from the past which has worked - same effect as above.

**Comment by fbngrmr** [comment]
Hey,

I'm glad you find `audiotheker` useful and thanks for informing me that there might be an issue with `audiotheker` 😊

I was unable to reproduce the issue - perhaps it was just a temporary problem with the ARD Audiothek?

I definitely need to add some more logging output to indicate what's happening 🙈

**Comment by wieland-s** [comment]
You're right, it works now. Thanks for your attention anyway. Probably really a temporary problem.
